cask_args appdir: "/Applications"

brew "jq"
brew "tree"
brew "git"
brew "starship"
brew "neovim"
brew "zsh-completions"
brew "font-hackgen"
brew "font-hackgen-nerd"
brew "mise"
brew "zsh-autocomplete"

cask "docker"
cask "dbeaver-community"
cask "discord"
cask "keyboardcleantool"
cask "kindle"
cask "raycast"
cask "visual-studio-code"
cask "wezterm"
cask "zed"
cask "cursor"
cask "karabiner-elements"
cask "font-commit-mono"

# プライベート用(仕事用のmacはデフォルトで設定されている可能性があるため)
# cask "figma"
# cask "zoom"
# cask "firefox"
# cask "google-chrome"
