cask_args appdir: "/Applications"

brew "docker"
brew "jq"
brew "tree"
brew "git"
brew "bun"
brew "starship"
brew "neovim"
brew "zsh-completions"

cask "dbeaver-community"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "keyboardcleantool"
cask "kindle"
cask "raycast"
cask "visual-studio-code"
cask "zoom"
cask "wezterm"
cask "zed"
cask "cursor"
cask "arc"
cask "karabiner-elements"
cask "figma"
